---
triggers:
  - action: email
    condition: failure
    to: parasrah <dev@parasrah.com>
image: nixos/unstable
packages:
  - nixos.zip
  - nixos.hut
sources:
  - git@git.sr.ht:~parasrah/alt-drag
secrets:
  - 8a8497a8-d217-4d4e-892f-ff4499b0c4cf
  - 788772b2-c7db-44f1-930f-9d37c016734d
tasks:
  - release: |
      if [[ "$GIT_REF" != refs/tags/* ]]; then
        exit 0
      fi

      tag="$(basename "$GIT_REF")"
      binary="$HOME/alt-drag_${tag}.zip"

      cd alt-drag/

      zip -r "$binary" .

      hut git artifact upload \
          --repo ~parasrah/alt-drag \
          --rev $GIT_REF \
          "$binary"
